module.exports = {
    INTEGER_LITERAL: "INTEGER_LITERAL",
    IDENTIFIER: "IDENTIFIER",
    LEFT_PAREN: "LEFT_PAREN",
    RIGHT_PAREN: "RIGHT_PAREN",
    END_OF_LINE: "END_OF_LINE",
    COMMA: "COMMA",
    LEFT_CURLY_BRACE: "LEFT_CURLY_BRACE",
    RIGHT_CURLY_BRACE: "RIGHT_CURLY_BRACE",
    END_OF_FILE: "END_OF_FILE",

    //Operators
    PLUS: "PLUS", MINUS: "MINUS", STAR: "STAR", SLASH: "SLASH", BANG: "BANG",
    EQUAL: "EQUAL",
    EQUAL_EQUAL: "EQUAL_EQUAL", BANG_EQUAL: "BANG_EQUAL",
    GREATER: "GREATER", LESS: "LESS", GREATER_EQUAL: "GREATER_EQUAL", LESS_EQUAL: "LESS_EQUAL",
    PIPE: "PIPE", PIPE_PIPE: "PIPE_PIPE",
    AND: "AND", AND_AND: "AND_AND",

    //Keywords
    KEYWORD_RETURN: "KEYWORD_RETURN"
};
