module.exports = {
    INTEGER_LITERAL: "INTEGER_LITERAL",
    IDENTIFIER: "IDENTIFIER",
    LEFT_PAREN: "LEFT_PAREN",
    RIGHT_PAREN: "RIGHT_PAREN",
    END_OF_LINE: "END_OF_LINE",
    COMMA: "COMMA",
    LEFT_CURLY_BRACE: "LEFT_CURLY_BRACE",
    RIGHT_CURLY_BRACE: "RIGHT_CURLY_BRACE",
    END_OF_FILE: "END_OF_FILE",

    //Operators
    OPERATOR_ADD: "OPERATOR_ADD", OPERATOR_SUBTRACT: "OPERATOR_SUBTRACT", OPERATOR_MULTIPLY: "OPERATOR_MULTIPLY", OPERATOR_DIVIDE: "OPERATOR_DIVIDE",
    OPERATOR_NEGATE: "OPERATOR_NEGATE", OPERATOR_NOT: "OPERATOR_NOT",
    OPERATOR_ASSIGN: "OPERATOR_ASSIGN",
    OPERATOR_EQUALITY: "OPERATOR_EQUALITY", OPERATOR_NOT_EQUALITY: "OPERATOR_NOT_EQUALITY",
    OPERATOR_GREATER_THAN: "OPERATOR_GREATER_THAN", OPERATOR_LESS_THAN: "OPERATOR_LESS_THAN", OPERATOR_GREATER_THAN_OR_EQUAL: "OPERATOR_GREATER_THAN_OR_EQUAL", OPERATOR_LESS_THAN_OR_EQUAL: "OPERATOR_LESS_THAN_OR_EQUAL",
    OPERATOR_BINARY_OR: "OPERATOR_BINARY_OR", OPERATOR_LOGICAL_OR: "OPERATOR_LOGICAL_OR",
    OPERATOR_BINARY_AND: "OPERATOR_BINARY_AND", OPERATOR_LOGICAL_AND: "OPERATOR_LOGICAL_AND",

    //Keywords
    KEYWORD_RETURN: "KEYWORD_RETURN"
};
