module.exports = {
    INTEGER_LITERAL: "INTEGER_LITERAL",
    STRING_LITERAL: "STRING_LITERAL",
    IDENTIFIER: "IDENTIFIER",
    LEFT_PAREN: "LEFT_PAREN",
    RIGHT_PAREN: "RIGHT_PAREN",
    END_OF_LINE: "END_OF_LINE",
    COMMA: "COMMA",
    LEFT_CURLY_BRACE: "LEFT_CURLY_BRACE",
    RIGHT_CURLY_BRACE: "RIGHT_CURLY_BRACE",
    LEFT_SQUARE_BRACE: "LEFT_SQUARE_BRACE",
    RIGHT_SQUARE_BRACE: "RIGHT_SQUARE_BRACE",
    END_OF_FILE: "END_OF_FILE",

    //Operators
    PLUS: "PLUS", MINUS: "MINUS", STAR: "STAR", SLASH: "SLASH", BANG: "BANG", PERCENT: "PERCENT",
	PLUS_PLUS: "PLUS_PLUS", MINUS_MINUS: "MINUS_MINUS",
    PLUS_EQUAL: "PLUS_EQUAL", MINUS_EQUAL: "MINUS_EQUAL", STAR_EQUAL: "STAR_EQUAL", SLASH_EQUAL: "SLASH_EQUAL",
    EQUAL: "EQUAL",
    EQUAL_EQUAL: "EQUAL_EQUAL", BANG_EQUAL: "BANG_EQUAL",
    GREATER: "GREATER", LESS: "LESS", GREATER_EQUAL: "GREATER_EQUAL", LESS_EQUAL: "LESS_EQUAL",
    PIPE: "PIPE", PIPE_PIPE: "PIPE_PIPE",
    AMPERSAND: "AMPERSAND", AMPERSAND_AMPERSAND: "AMPERSAND_AMPERSAND",

    //Keywords
    KEYWORD_RETURN: "KEYWORD_RETURN",
    KEYWORD_IF: "KEYWORD_IF",
    KEYWORD_WHILE: "KEYWORD_WHILE",
    KEYWORD_FOR: "KEYWORD_FOR",
    KEYWORD_IMPORT: "KEYWORD_IMPORT"
};
