module.exports = {
    //Expressions
    UNARY_EXPRESSION: "UNARY_EXPRESSION",
    BINARY_EXPRESSION: "BINARY_EXPRESSION",
    ASSIGNMENT_EXPRESSION: "ASSIGNMENT_EXPRESSION",
    CALL_EXPRESSION: "CALL_EXPRESSION",
    INTEGER_LITERAL: "INTEGER_LITERAL",
    STRING_LITERAL: "STRING_LITERAL",
    VARIABLE: "VARIABLE",

    //Declarations
    FUNCTION_DECLARATION: "FUNCTION_DECLARATION",
    VARIABLE_DECLARATION: "VARIABLE_DECLARATION",

    //Statements
    EXPRESSION_STATEMENT: "EXPRESSION_STATEMENT",
    RETURN_STATEMENT: "RETURN_STATEMENT",

    PARAMETER: "PARAMETER",
    NONE: "NONE"
};
