module.exports = {
    //Expressions
    UNARY_EXPRESSION: "UNARY_EXPRESSION",
    BINARY_EXPRESSION: "BINARY_EXPRESSION",
    ASSIGNMENT_EXPRESSION: "ASSIGNMENT_EXPRESSION",
    CALL_EXPRESSION: "CALL_EXPRESSION",
    INTEGER_LITERAL: "INTEGER_LITERAL",
    STRING_LITERAL: "STRING_LITERAL",
    CHARACTER_LITERAL: "CHARACTER_LITERAL",
    ARRAY: "ARRAY",
    VARIABLE: "VARIABLE",

    //Declarations
    FUNCTION_DECLARATION: "FUNCTION_DECLARATION",
    VARIABLE_DECLARATION: "VARIABLE_DECLARATION",

    //Statements
    EXPRESSION_STATEMENT: "EXPRESSION_STATEMENT",
    RETURN_STATEMENT: "RETURN_STATEMENT",
    IF_STATEMENT: "IF_STATEMENT",
    WHILE_STATEMENT: "WHILE_STATEMENT",
    FOR_STATEMENT: "FOR_STATEMENT",
    IMPORT_STATEMENT: "IMPORT_STATEMENT",

	DATA_TYPE: "DATA_TYPE",
    PARAMETER: "PARAMETER",
    NONE: "NONE"
};
